#!/usr/bin/env python3
import os
import glob

output_file = "certs_bundle.h"
certs_dir = "certs"

header_content = """/* Auto-generated by generate_certs.py - Do not edit */
#ifndef CERTS_BUNDLE_H
#define CERTS_BUNDLE_H

static const char *ca_certs_bundle[] = {
"""

pem_files = glob.glob(os.path.join(certs_dir, "*.pem"))

for pem_path in pem_files:
    print(f"Bundling certificate: {pem_path}")
    with open(pem_path, "r") as f:
        lines = f.readlines()
    
    header_content += "    \""
    for line in lines:
        # Strip trailing newlines and escape quotes/newlines for a clean C-string literal
        clean_line = line.replace("\r", "").replace("\n", "").replace('"', '\\"')
        header_content += clean_line + "\\n"
    header_content += "\",\n"

# Add the final null terminator array element
header_content += """    0 // Null terminator
};

#endif
"""

with open(output_file, "w") as f:
    f.write(header_content)
